; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[platformio]
default_envs = serial

[common]
platform = espressif8266
framework = arduino
board = nodemcuv2
monitor_speed = 115200
board_build.filesystem = littlefs
lib_deps =
  adafruit/Adafruit Unified Sensor @ ^1.1.15
  adafruit/DHT sensor library @ ^1.4.6
  adafruit/Adafruit AHTX0 @ ^2.0.5
  me-no-dev/ESPAsyncWebServer @ ^1.2.3
  me-no-dev/ESPAsyncTCP @ ^1.2.0
  bblanchon/ArduinoJson @ ^6.21.3
 
[env:serial]
extends = common
upload_protocol = esptool

[env:ota]
extends = common
; run using pio run -t upload -e ota (prunu -e ota)
upload_protocol = espota
extra_scripts = pre:ota_config.py
